package com.lucas.devicesapijavamvc.kafka;

import com.lucas.devicesapijavamvc.domain.Device;
import com.lucas.devicesapijavamvc.domain.DeviceState;
import com.lucas.devicesapijavamvc.repository.DeviceRepository;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.time.OffsetDateTime;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class DeviceEventListenerTest {

    @Mock
    DeviceRepository repo;

    @Test
    @DisplayName("onDeviceEvent() should ignore events with origin = JAVA")
    void onDeviceEventShouldIgnoreOwnEvents() {
        DeviceEventListener listener = new DeviceEventListener(repo);

        DeviceEvent event = new DeviceEvent(
                UUID.randomUUID(),
                "iPhone 15",
                "Apple",
                DeviceState.AVAILABLE.name(),
                OffsetDateTime.now(),
                "JAVA" // origin from this app
        );

        listener.onDeviceEvent(event);

        verifyNoInteractions(repo);
    }

    @Test
    @DisplayName("onDeviceEvent() should update existing device when externalId already exists")
    void onDeviceEventShouldUpdateExistingDevice() {
        DeviceEventListener listener = new DeviceEventListener(repo);

        UUID externalId = UUID.randomUUID();
        Device existing = Device.fromEvent(
                externalId,
                "Old Name",
                "Old Brand",
                DeviceState.AVAILABLE,
                OffsetDateTime.now().minusDays(1)
        );

        when(repo.findByExternalId(externalId)).thenReturn(Optional.of(existing));
        when(repo.save(any(Device.class))).thenAnswer(inv -> inv.getArgument(0));

        DeviceEvent event = new DeviceEvent(
                externalId,
                "New Name",
                "New Brand",
                DeviceState.IN_USE.name(),
                existing.getCreationTime(), // keep same creation time in event
                "KOTLIN" // coming from Kotlin app
        );

        listener.onDeviceEvent(event);

        ArgumentCaptor<Device> deviceCaptor = ArgumentCaptor.forClass(Device.class);
        verify(repo).findByExternalId(externalId);
        verify(repo).save(deviceCaptor.capture());
        verifyNoMoreInteractions(repo);

        Device saved = deviceCaptor.getValue();
        assertThat(saved.getExternalId()).isEqualTo(externalId);
        assertThat(saved.getName()).isEqualTo("New Name");
        assertThat(saved.getBrand()).isEqualTo("New Brand");
        assertThat(saved.getState()).isEqualTo(DeviceState.IN_USE);
        assertThat(saved.getCreationTime()).isEqualTo(existing.getCreationTime());
    }

    @Test
    @DisplayName("onDeviceEvent() should create new mirrored device when externalId does not exist")
    void onDeviceEventShouldCreateNewDeviceWhenNotExists() {

        DeviceEventListener listener = new DeviceEventListener(repo);

        UUID externalId = UUID.randomUUID();
        OffsetDateTime creationTime = OffsetDateTime.now().minusHours(1);

        when(repo.findByExternalId(externalId)).thenReturn(Optional.empty());
        when(repo.save(any(Device.class))).thenAnswer(inv -> inv.getArgument(0));

        DeviceEvent event = new DeviceEvent(
                externalId,
                "Pixel 9",
                "Google",
                DeviceState.AVAILABLE.name(),
                creationTime,
                "KOTLIN"
        );


        listener.onDeviceEvent(event);

        ArgumentCaptor<Device> deviceCaptor = ArgumentCaptor.forClass(Device.class);
        verify(repo).findByExternalId(externalId);
        verify(repo).save(deviceCaptor.capture());
        verifyNoMoreInteractions(repo);

        Device saved = deviceCaptor.getValue();
        assertThat(saved.getId()).isNull(); // mirrored: id generated by DB later
        assertThat(saved.getExternalId()).isEqualTo(externalId);
        assertThat(saved.getName()).isEqualTo("Pixel 9");
        assertThat(saved.getBrand()).isEqualTo("Google");
        assertThat(saved.getState()).isEqualTo(DeviceState.AVAILABLE);
        assertThat(saved.getCreationTime()).isEqualTo(creationTime);
    }
}
