services:
  # ===== Java stack =====
  java-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: devicesdb
      POSTGRES_USER: devices
      POSTGRES_PASSWORD: devices
    ports:
      - "5432:5432"
    volumes:
      - java_dbdata:/var/lib/postgresql/data

  java-app:
    build:
      context: ./devices-api-java-mvc
    depends_on:
      - java-db
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: docker,kafka
    ports:
      - "8080:8080"

  # ===== Kotlin stack =====
  kotlin-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: devicesdb_rx
      POSTGRES_USER: devices
      POSTGRES_PASSWORD: devices
    ports:
      - "5433:5432"
    volumes:
      - kotlin_dbdata:/var/lib/postgresql/data

  kotlin-app:
    build:
      context: ./devices-api-kotlin-reactive
    depends_on:
      - kotlin-db
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: docker,kafka
    ports:
      - "8081:8081"

  # ===== Kafka stack =====
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  java_dbdata:
  kotlin_dbdata:
