spring:
  application:
    name: devices-api-java-mvc

  datasource:
    url: jdbc:postgresql://localhost:5432/devicesdb
    username: devices
    password: devices
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

kafka:
  enabled: false
  bootstrap-servers: kafka:9092
  topic:
    devices: devices.events

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://java-db:5432/devicesdb
    username: devices
    password: devices

---
spring:
  config:
    activate:
      on-profile: kafka

kafka:
  enabled: true

